"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const screen=$("#gameScreen"),box=$("#gameBox");
const meta={
 runner:["Runaway Spirit","ACCIÓN · TRES FASES","●","Cruza el bosque, el hielo y la montaña. Toca para saltar, vuelve a tocar en el aire para doble salto y desliza a la derecha para usar el dash.","Reúne energía, conserva tu escudo y rompe el portal final."],
 weaver:["Aurora Weaver","DESTREZA · CONSTELACIONES","✦","Memoriza una forma, dibuja sus estrellas en orden y evita las estrellas oscuras. Los puntos se mueven y el tiempo se reduce en cada ronda.","La precisión alimenta el combo; un error lo devuelve a cero."],
 wolf:["Whispering Wolf","SONIDO · MEMORIA","◢","Escucha secuencias graves, medias y agudas. Repítelas en los tres caminos antes de que despierte el lobo.","Usa audífonos o sube un poco el volumen para sentir cada tono."],
 moths:["Moon Moths","CONTROL · BANDADA","⋈","Arrastra la luna para conducir una bandada. Encadena flores, evita sombras y resiste las corrientes que empujan a tus polillas.","Cuantas más polillas conserves, mayor será tu multiplicador."],
 seed:["The Seed Sings","RITMO · CRECIMIENTO","⌇","Escucha una melodía y repítela con el ritmo correcto. Los golpes perfectos hacen crecer flores especiales y ramas más luminosas.","No basta con pulsar el símbolo correcto: también importa cuándo lo haces."],
 storm:["Dance in the Storm","ARCADE · OLEADAS","ϟ","Desliza entre tres carriles, esquiva lluvia oscura y recoge relámpagos. Llena la carga para activar una explosión protectora.","La tormenta cambia de patrón cada quince segundos."]
};
const old=JSON.parse(localStorage.getItem("hidden_queendom_v1")||"{}");
const state={game:null,score:0,timers:[],intervals:[],raf:0,retry:null,cleanups:[],data:JSON.parse(localStorage.getItem("hidden_queendom_v3")||JSON.stringify({total:old.total||0,played:old.played||0,best:old.best||{},count:old.count||{},achievements:{}}))};
function timer(id){state.timers.push(id);return id}function every(id){state.intervals.push(id);return id}function cleanup(fn){state.cleanups.push(fn);return fn}
function clearGame(){state.timers.forEach(clearTimeout);state.intervals.forEach(clearInterval);state.timers=[];state.intervals=[];state.cleanups.forEach(fn=>{try{fn()}catch(e){}});state.cleanups=[];if(state.raf)cancelAnimationFrame(state.raf);state.raf=0;box.innerHTML=""}
function score(n){state.score=Math.max(0,Math.round(n));$("#live").textContent=state.score}
function haptic(pattern=12){try{navigator.vibrate&&navigator.vibrate(pattern)}catch(e){}}
function save(){localStorage.setItem("hidden_queendom_v3",JSON.stringify(state.data));refresh()}
function refresh(){
 $("#total").textContent=state.data.total||0;$("#played").textContent=state.data.played||0;
 Object.keys(meta).forEach(k=>{const el=$("#rec-"+k);if(el)el.textContent="Récord "+((state.data.best||{})[k]||0)});
 const counts=Object.entries(state.data.count||{}).sort((a,b)=>b[1]-a[1]);$("#crown").textContent=counts.length?meta[counts[0][0]][0].split(" ")[0]:"—";
}
function progress(value){const el=$("#gameProgress");if(el)el.style.width=Math.max(0,Math.min(100,value))+"%"}
function comboToast(text){let el=$(".combo-toast");if(!el){el=document.createElement("div");el.className="combo-toast";box.appendChild(el)}el.textContent=text;el.classList.remove("show");requestAnimationFrame(()=>el.classList.add("show"));timer(setTimeout(()=>el.classList.remove("show"),650))}
function gameHeader(text="PREPÁRATE"){return `<div class="hud" id="hud">${text}</div><div class="progress-shell"><div class="progress-fill" id="gameProgress"></div></div>`}
function openGame(k){clearGame();state.game=k;state.retry=()=>openGame(k);score(0);$("#gameName").textContent=meta[k][0];$("#gameSub").textContent=meta[k][1];screen.classList.add("open");document.body.style.overflow="hidden";AudioFX.setMood(k);
 box.innerHTML=`<div class="panel intro"><div class="big">${meta[k][2]}</div><h3>${meta[k][0]}</h3><p>${meta[k][3]}</p><div class="tip">${meta[k][4]}</div><button class="primary" id="start">Comenzar viaje</button></div>`;
 $("#start").onclick=()=>{AudioFX.resume();AudioFX.sfx("start");haptic(18);({runner:startRunner,weaver:startWeaver,wolf:startWolf,moths:startMoths,seed:startSeed,storm:startStorm})[k]()}}
function closeGame(){clearGame();screen.classList.remove("open");document.body.style.overflow="";state.game=null;AudioFX.setMood("home")}
function finish(points,title,text,icon="✦"){clearGame();score(points);state.data.total=(state.data.total||0)+points;state.data.played=(state.data.played||0)+1;state.data.best=state.data.best||{};state.data.count=state.data.count||{};state.data.best[state.game]=Math.max(state.data.best[state.game]||0,points);state.data.count[state.game]=(state.data.count[state.game]||0)+1;save();$("#rIcon").textContent=icon;$("#rTitle").textContent=title;$("#rText").textContent=text;$("#rPoints").textContent=points;$("#result").classList.add("show");AudioFX.sfx("win");haptic([20,40,25,50,35])}
$$('.chapter').forEach(b=>b.onclick=()=>openGame(b.dataset.game));$("#back").onclick=closeGame;$("#rHome").onclick=()=>{$("#result").classList.remove("show");closeGame()};$("#rRetry").onclick=()=>{$("#result").classList.remove("show");state.retry()};

const AudioFX=(()=>{
 let ctx,master,music,sfx,filter,drone=[],enabled=true,mood="home",chord=0,arpId=null,wind;
 const moods={
  home:{roots:[55,65.41,73.42,49],scale:[0,3,7,10,12],tempo:920},runner:{roots:[65.41,73.42,82.41,55],scale:[0,5,7,10,12],tempo:520},weaver:{roots:[73.42,87.31,65.41,98],scale:[0,2,7,9,14],tempo:740},wolf:{roots:[49,55,46.25,41.2],scale:[0,3,5,10,12],tempo:1080},moths:{roots:[87.31,73.42,98,65.41],scale:[0,4,7,11,14],tempo:680},seed:{roots:[65.41,82.41,73.42,98],scale:[0,2,4,7,9,12],tempo:610},storm:{roots:[55,61.74,49,65.41],scale:[0,3,6,7,10,12],tempo:430}}
 };
 function init(){if(ctx)return;ctx=new (window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();music=ctx.createGain();sfx=ctx.createGain();filter=ctx.createBiquadFilter();master.gain.value=.85;music.gain.value=.2;sfx.gain.value=.62;filter.type="lowpass";filter.frequency.value=950;music.connect(filter).connect(master);sfx.connect(master);master.connect(ctx.destination);
  for(let i=0;i<3;i++){const o=ctx.createOscillator(),g=ctx.createGain();o.type=i===0?"sine":"triangle";g.gain.value=i===0?.032:.013;o.connect(g).connect(music);o.start();drone.push(o)}
  const buf=ctx.createBuffer(1,ctx.sampleRate*4,ctx.sampleRate),d=buf.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(.5-.25*i/d.length);const src=ctx.createBufferSource(),wg=ctx.createGain(),wf=ctx.createBiquadFilter();src.buffer=buf;src.loop=true;wf.type="lowpass";wf.frequency.value=500;wg.gain.value=.024;src.connect(wf).connect(wg).connect(music);src.start();wind=src;setMood("home")}
 function setMood(name){mood=moods[name]?name:"home";if(!ctx)return;const m=moods[mood],root=m.roots[chord%m.roots.length],t=ctx.currentTime;drone.forEach((o,i)=>o.frequency.exponentialRampToValueAtTime(root*[1,1.5,2][i],t+1.8));filter.frequency.exponentialRampToValueAtTime(mood==="storm"?680:mood==="wolf"?570:1050,t+1.1);if(arpId)clearInterval(arpId);arpId=setInterval(()=>{if(!enabled||!ctx)return;const mm=moods[mood],r=mm.roots[chord%mm.roots.length],semi=mm.scale[Math.floor(Math.random()*mm.scale.length)],f=r*Math.pow(2,semi/12)*2;note(f,.32,.018,Math.random()>.75?"triangle":"sine",music);if(Math.random()>.78){chord=(chord+1)%mm.roots.length;const nr=mm.roots[chord];drone.forEach((o,i)=>o.frequency.exponentialRampToValueAtTime(nr*[1,1.5,2][i],ctx.currentTime+1.6))}},m.tempo)}
 function note(f,d=.1,v=.06,type="sine",dest=sfx,when=0){if(!ctx||!enabled)return;const o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+when;o.type=type;o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(v,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g).connect(dest);o.start(t);o.stop(t+d+.03)}
 function noise(d=.14,v=.045,high=900){if(!ctx||!enabled)return;const b=ctx.createBuffer(1,ctx.sampleRate*d,ctx.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=Math.random()*2-1;const src=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain();src.buffer=b;f.type="highpass";f.frequency.value=high;g.gain.setValueAtTime(v,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+d);src.connect(f).connect(g).connect(sfx);src.start()}
 function sfxPlay(n){if(!enabled)return;({start:()=>{note(392,.13,.07);note(587.33,.2,.055,"sine",sfx,.08)},collect:()=>{note(659,.08,.07);note(987.77,.13,.05,"sine",sfx,.045)},hit:()=>{note(92,.24,.08,"sawtooth");noise(.18,.05,200)},jump:()=>note(293.66,.1,.06,"triangle"),dash:()=>{noise(.2,.05,1200);note(196,.18,.045,"sawtooth")},shield:()=>{[392,523,784].forEach((f,i)=>note(f,.22,.045,"sine",sfx,i*.04))},good:()=>{note(523,.1,.06);note(783.99,.16,.05,"sine",sfx,.06)},perfect:()=>{[523,659,784,1047].forEach((f,i)=>note(f,.2,.045,"sine",sfx,i*.045))},bad:()=>note(138.59,.22,.075,"square"),boss:()=>{note(73.42,.55,.08,"sawtooth");noise(.35,.04,100)},win:()=>{[392,523,659,784,1047].forEach((f,i)=>note(f,.42,.05,"sine",sfx,i*.09))}}[n]||(()=>{}))()}
 function cue(i,when=0){[196,392,783.99][i]&&note([196,392,783.99][i],.42,.1,"sine",sfx,when)}
 function toggle(){enabled=!enabled;if(master)master.gain.setTargetAtTime(enabled?.85:.0001,ctx.currentTime,.08);return enabled}
 return{init,setMood,note,noise,sfx:sfxPlay,cue,toggle,resume(){if(ctx&&ctx.state==="suspended")ctx.resume()},get enabled(){return enabled}}
})();
$("#enter").onclick=()=>{AudioFX.init();AudioFX.resume();$("#splash").classList.add("hide");haptic(20)};$("#audioBtn").onclick=()=>{AudioFX.resume();const on=AudioFX.toggle();$("#audioBtn").textContent=on?"◖":"×"};document.addEventListener("visibilitychange",()=>{if(!document.hidden)AudioFX.resume()});

(()=>{const c=$("#sky"),x=c.getContext("2d");let stars=[],dust=[],w=0,h=0,dpr=1;function resize(){dpr=Math.min(2,devicePixelRatio||1);w=innerWidth;h=innerHeight;c.width=w*dpr;c.height=h*dpr;c.style.width=w+"px";c.style.height=h+"px";x.setTransform(dpr,0,0,dpr,0,0);stars=Array.from({length:Math.min(120,Math.floor(w*h/5800))},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*1.25+.2,a:Math.random()*.58+.15,p:Math.random()*6.28}));dust=Array.from({length:18},()=>({x:Math.random()*w,y:Math.random()*h,v:.08+Math.random()*.18,r:1+Math.random()*2,p:Math.random()*6.28}))}addEventListener("resize",resize);resize();function draw(t){x.clearRect(0,0,w,h);stars.forEach(s=>{const a=s.a*(.66+.34*Math.sin(t*.0013+s.p));x.fillStyle=`rgba(226,255,247,${a})`;x.beginPath();x.arc(s.x,s.y,s.r,0,7);x.fill()});dust.forEach(d=>{d.y-=d.v;d.x+=Math.sin(t*.0006+d.p)*.08;if(d.y<-8){d.y=h+8;d.x=Math.random()*w}x.shadowColor="#a5ffe0";x.shadowBlur=10;x.fillStyle="rgba(202,255,238,.24)";x.beginPath();x.arc(d.x,d.y,d.r,0,7);x.fill();x.shadowBlur=0});requestAnimationFrame(draw)}requestAnimationFrame(draw)})();
refresh();