const point=(e,c)=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const hitCircle=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y)<(a.r||0)+(b.r||0);

/* 1 · RUNAWAY SPIRIT — double jump, dash, energy burst and portal boss */
function startRunner(){
 box.innerHTML=gameHeader("❤❤❤ · BOSQUE VIVO")+`<canvas class="game" id="c" width="540" height="720"></canvas><div class="control-row"><button class="control-btn" id="jump"><b>↑</b><small>SALTO DOBLE</small></button><button class="control-btn" id="dash"><b>→</b><small>DASH · 30</small></button><button class="control-btn" id="burst"><b>✦</b><small>EXPLOSIÓN</small></button></div><div class="runner-help">Toca el escenario para saltar · desliza a la derecha para dash</div>`;
 const c=$("#c"),g=c.getContext("2d"),W=c.width,H=c.height,ground=620;
 let p={x:92,y:ground-25,vy:0,r:25,jumps:0,dash:0,inv:0},obs=[],orbs=[],particles=[],hearts=3,energy=0,combo=0,dist=0,collected=0,last=performance.now(),spawn=0,orbSpawn=.4,elapsed=0,ended=false,boss=false,bossHP=7,bossShot=0,portalPulse=0,sx=0,sy=0;
 function phaseName(){return elapsed<14?"BOSQUE VIVO":elapsed<28?"LAGO HELADO":elapsed<40?"MONTAÑA ALTA":"PORTAL DE SOMBRA"}
 function jump(){if(ended)return;if(p.jumps<2){p.vy=p.jumps? -650:-720;p.jumps++;AudioFX.sfx("jump");haptic(8)}}
 function dash(){if(ended||energy<30||p.dash>0)return;energy-=30;p.dash=.42;p.inv=.5;AudioFX.sfx("dash");haptic(18);combo++}
 function burst(){if(ended||energy<100)return;energy=0;p.inv=2.2;obs.forEach(o=>{if(o.type==="shot"&&boss){bossHP--;collected+=28}particles.push({x:o.x,y:o.y,vx:(Math.random()-.5)*220,vy:(Math.random()-.5)*220,a:1})});obs=[];AudioFX.sfx("shield");haptic([20,30,20]);combo+=3;comboToast("Luz salvaje")}
 $("#jump").onclick=jump;$("#dash").onclick=dash;$("#burst").onclick=burst;c.onpointerdown=e=>{sx=e.clientX;sy=e.clientY};c.onpointerup=e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy))dash();else jump()};
 function addObstacle(){const type=Math.random()<.2&&elapsed>8?"branch":"spike";obs.push(type==="branch"?{type,x:W+60,y:ground-125,w:80,h:30}:{type,x:W+50,y:ground-48,w:42+Math.random()*32,h:48})}
 function damage(){if(p.inv>0)return;hearts--;combo=0;p.inv=1.35;AudioFX.sfx("hit");haptic([35,35,35]);if(hearts<=0){ended=true;finish(Math.round(dist)+collected,"El espíritu perdió el sendero","Llegaste al "+phaseName().toLowerCase()+". Usa el dash y la explosión para conservar los corazones.","●")}}
 function loop(now){if(ended)return;const dt=Math.min(.033,(now-last)/1000);last=now;elapsed+=dt;dist+=dt*(16+elapsed*.34);spawn-=dt;orbSpawn-=dt;bossShot-=dt;portalPulse+=dt;
  const speed=270+elapsed*4+(p.dash>0?240:0);p.dash=Math.max(0,p.dash-dt);p.inv=Math.max(0,p.inv-dt);p.vy+=1780*dt;p.y+=p.vy*dt;if(p.y>=ground-p.r){p.y=ground-p.r;p.vy=0;p.jumps=0}
  if(!boss&&elapsed>=40){boss=true;obs=[];AudioFX.sfx("boss");comboToast("PORTAL FINAL")}
  if(!boss&&spawn<=0){addObstacle();spawn=Math.max(.48,1.05-elapsed*.011)+Math.random()*.55}
  if(orbSpawn<=0){orbs.push({x:W+30,y:250+Math.random()*300,r:11,kind:Math.random()<.1?"shield":"light"});orbSpawn=.45+Math.random()*.65}
  if(boss&&bossShot<=0){const lane=Math.random()<.5?ground-35:390+Math.random()*130;obs.push({type:"shot",x:W-105,y:lane,r:18,vx:-260-Math.random()*100});bossShot=.55+Math.random()*.45}
  obs.forEach(o=>{o.x+=(o.vx||-speed)*dt});orbs.forEach(o=>o.x-=speed*dt);
  for(let i=obs.length-1;i>=0;i--){const o=obs[i];if(o.x+(o.w||o.r||20)<-40){obs.splice(i,1);continue}let hit=false;if(o.type==="shot")hit=hitCircle(p,o);else hit=p.x+p.r>o.x&&p.x-p.r<o.x+o.w&&p.y+p.r>o.y&&p.y-p.r<o.y+o.h;if(hit){if(p.dash>0&&o.type==="shot"){bossHP--;collected+=30;energy=clamp(energy+18,0,100);AudioFX.sfx("perfect");haptic(12);obs.splice(i,1);combo++;comboToast("Reflejo ×"+combo)}else{obs.splice(i,1);damage()}}}
  for(let i=orbs.length-1;i>=0;i--){const o=orbs[i];if(o.x<-30){orbs.splice(i,1);continue}if(hitCircle(p,o)){orbs.splice(i,1);if(o.kind==="shield"){p.inv=2.5;AudioFX.sfx("shield");comboToast("Escudo espiritual")}else{energy=clamp(energy+10,0,100);collected+=8*(1+Math.min(combo,5)*.12);combo++;if(combo%5===0)comboToast("Combo ×"+combo);AudioFX.sfx("collect")}}}
  particles.forEach(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.a-=dt*1.7});particles=particles.filter(q=>q.a>0);
  if(boss&&bossHP<=0){ended=true;finish(Math.round(dist)+collected+350,"Rompiste el portal de sombra","Completaste los tres mundos y devolviste la luz a la montaña.","●");return}if(elapsed>58&&boss){ended=true;finish(Math.round(dist)+collected,"El portal siguió abierto","Llegaste al jefe. Devuelve sus proyectiles usando dash o llena la explosión.","●");return}
  score(Math.round(dist)+Math.round(collected));progress(boss?(7-bossHP)/7*100:elapsed/40*100);$("#hud").innerHTML=`<span class="hud-chip">${"❤".repeat(hearts)}${"♡".repeat(3-hearts)}</span><span>${phaseName()}</span><span class="hud-chip">✦ ${Math.round(energy)}${boss?" · PORTAL "+bossHP:""}</span>`;
  draw();state.raf=requestAnimationFrame(loop)}
 function draw(){let bg=g.createLinearGradient(0,0,0,H);if(elapsed<14){bg.addColorStop(0,"#143b3a");bg.addColorStop(1,"#071316")}else if(elapsed<28){bg.addColorStop(0,"#243957");bg.addColorStop(1,"#08101c")}else{bg.addColorStop(0,"#252944");bg.addColorStop(1,"#080b13")}g.fillStyle=bg;g.fillRect(0,0,W,H);
  g.globalAlpha=.18;for(let i=0;i<8;i++){g.fillStyle=i%2?"#9cfadd":"#9dd5ff";g.beginPath();g.arc((i*100-dist*5)%700,100+i*43,48+i*4,0,7);g.fill()}g.globalAlpha=1;
  g.fillStyle="#05090d";g.fillRect(0,ground,W,H-ground);for(let x=-40;x<W+80;x+=65){g.fillStyle="#071016";g.beginPath();g.moveTo(x,ground);g.lineTo(x+34,ground-110-(x%4)*10);g.lineTo(x+68,ground);g.fill()}
  obs.forEach(o=>{if(o.type==="shot"){g.shadowColor="#c084ff";g.shadowBlur=25;g.fillStyle="#3e1f5e";g.beginPath();g.arc(o.x,o.y,o.r,0,7);g.fill();g.shadowBlur=0}else{g.fillStyle=o.type==="branch"?"#152421":"#192629";g.beginPath();if(o.type==="branch")g.roundRect(o.x,o.y,o.w,o.h,10);else{g.moveTo(o.x,o.y+o.h);g.lineTo(o.x+o.w*.25,o.y);g.lineTo(o.x+o.w*.55,o.y+o.h*.55);g.lineTo(o.x+o.w*.78,o.y+4);g.lineTo(o.x+o.w,o.y+o.h)}g.fill()}});
  orbs.forEach(o=>{g.shadowColor=o.kind==="shield"?"#ffe09a":"#9cffd9";g.shadowBlur=24;g.fillStyle=o.kind==="shield"?"#fff1bd":"#effff9";g.beginPath();g.arc(o.x,o.y,o.r+(o.kind==="shield"?4:0),0,7);g.fill();g.shadowBlur=0});
  if(boss){g.save();g.translate(W-74,315);g.rotate(portalPulse*.35);g.strokeStyle="#bc8cff";g.lineWidth=12;g.shadowColor="#a45cff";g.shadowBlur=35;g.beginPath();g.arc(0,0,55+Math.sin(portalPulse*3)*4,0,7);g.stroke();g.restore();g.shadowBlur=0}
  particles.forEach(q=>{g.globalAlpha=q.a;g.fillStyle="#dffff3";g.fillRect(q.x,q.y,3,3)});g.globalAlpha=1;
  if(p.inv>0&&Math.floor(p.inv*12)%2===0)g.globalAlpha=.35;g.shadowColor=p.dash>0?"#fff3ae":"#8dffe0";g.shadowBlur=p.dash>0?42:25;g.fillStyle="#f5fffb";g.beginPath();g.arc(p.x,p.y,p.r,0,7);g.fill();g.fillStyle="#061016";g.beginPath();g.arc(p.x+7,p.y-5,3,0,7);g.fill();g.shadowBlur=0;g.globalAlpha=1;
 }
 state.raf=requestAnimationFrame(loop)
}

/* 2 · AURORA WEAVER — moving constellations, memory, hazards and lives */
function startWeaver(){
 box.innerHTML=gameHeader("MEMORIZA EL CIELO")+`<canvas class="game" id="c" width="540" height="690"></canvas><div class="runner-help">Mantén el dedo y atraviesa las estrellas en orden · evita las sombras</div>`;
 const c=$("#c"),g=c.getContext("2d"),W=c.width,H=c.height;let round=0,nodes=[],hazards=[],next=0,drawing=false,trail=[],showing=true,lives=3,combo=0,roundStart=0,timeLimit=0,last=performance.now(),ended=false,sx=0,sy=0;
 function newRound(){round++;if(round>7){ended=true;finish(state.score+180,"Tejiste el cielo completo","Siete constelaciones quedaron encendidas sobre el Queendom.","✦");return}next=0;trail=[];showing=true;drawing=false;nodes=[];hazards=[];const count=3+round;for(let i=0;i<count;i++){const a=i/count*Math.PI*2+Math.random()*.5,r=95+Math.random()*120;nodes.push({x:W/2+Math.cos(a)*r,y:H/2+Math.sin(a)*r,r:17,vx:(Math.random()-.5)*(8+round*2),vy:(Math.random()-.5)*(8+round*2)})}for(let i=0;i<Math.floor(round/2);i++)hazards.push({x:70+Math.random()*(W-140),y:100+Math.random()*(H-200),r:25+Math.random()*12,vx:(Math.random()-.5)*45,vy:(Math.random()-.5)*45});timeLimit=Math.max(4.5,8-round*.48);$("#hud").textContent=`CONSTELACIÓN ${round}/7 · MEMORIZA`;progress((round-1)/7*100);draw();timer(setTimeout(()=>{showing=false;roundStart=performance.now();$("#hud").innerHTML=`<span class="hud-chip">${"◆".repeat(lives)}${"◇".repeat(3-lives)}</span><span>DIBUJA · ${timeLimit.toFixed(1)}s</span><span class="hud-chip">COMBO ${combo}</span>`},1700+round*80))}
 function fail(reason){if(showing||ended)return;lives--;combo=0;next=0;trail=[];drawing=false;AudioFX.sfx("bad");haptic([18,30,18]);comboToast(reason);if(lives<=0){ended=true;finish(state.score,"El cielo se cerró","Llegaste a la constelación "+round+". Memoriza la forma antes de que los números desaparezcan.","✦")}else{showing=true;$("#hud").textContent="OBSERVA OTRA VEZ";timer(setTimeout(()=>{showing=false;roundStart=performance.now();$("#hud").textContent="DIBUJA LA CONSTELACIÓN"},1000))}}
 function complete(){const used=(performance.now()-roundStart)/1000,bonus=Math.round(80+round*18+Math.max(0,timeLimit-used)*22+combo*8);score(state.score+bonus);combo++;AudioFX.sfx(combo>2?"perfect":"good");haptic(14);comboToast(combo>2?"Constelación ×"+combo:"Constelación completa");timer(setTimeout(newRound,650))}
 c.onpointerdown=e=>{if(showing||ended)return;e.preventDefault();drawing=true;c.setPointerCapture(e.pointerId);trail=[];move(e)};c.onpointermove=e=>{if(drawing)move(e)};c.onpointerup=c.onpointercancel=()=>{if(drawing&&next<nodes.length)fail("Trazo incompleto");drawing=false};
 function move(e){const p=point(e,c);trail.push(p);for(const h of hazards)if(Math.hypot(p.x-h.x,p.y-h.y)<h.r+9){fail("Tocaste una sombra");return}const n=nodes[next];if(n&&Math.hypot(p.x-n.x,p.y-n.y)<n.r+17){next++;AudioFX.sfx("collect");haptic(5);if(next===nodes.length){drawing=false;complete()}}}
 function loop(now){if(ended)return;const dt=Math.min(.035,(now-last)/1000);last=now;if(!showing){nodes.forEach(n=>{n.x+=n.vx*dt;n.y+=n.vy*dt;if(n.x<n.r||n.x>W-n.r)n.vx*=-1;if(n.y<n.r+40||n.y>H-n.r)n.vy*=-1});hazards.forEach(h=>{h.x+=h.vx*dt;h.y+=h.vy*dt;if(h.x<h.r||h.x>W-h.r)h.vx*=-1;if(h.y<h.r||h.y>H-h.r)h.vy*=-1});const remain=timeLimit-(now-roundStart)/1000;if(remain<=0)fail("Se apagó la forma");else $("#hud").innerHTML=`<span class="hud-chip">${"◆".repeat(lives)}${"◇".repeat(3-lives)}</span><span>ESTRELLA ${Math.min(next+1,nodes.length)}/${nodes.length} · ${remain.toFixed(1)}s</span><span class="hud-chip">×${combo}</span>`}draw();state.raf=requestAnimationFrame(loop)}
 function draw(){const bg=g.createRadialGradient(W*.55,H*.2,10,W*.5,H*.5,H*.7);bg.addColorStop(0,"#24204a");bg.addColorStop(.45,"#10162d");bg.addColorStop(1,"#050912");g.fillStyle=bg;g.fillRect(0,0,W,H);for(let i=0;i<45;i++){const x=(i*97)%W,y=(i*163)%H;g.fillStyle=`rgba(225,235,255,${.16+(i%5)*.04})`;g.fillRect(x,y,1.5,1.5)}
  if(showing){g.strokeStyle="rgba(194,168,255,.65)";g.lineWidth=3;g.beginPath();nodes.forEach((n,i)=>i?g.lineTo(n.x,n.y):g.moveTo(n.x,n.y));g.stroke()}
  if(trail.length>1){g.strokeStyle="#baffdf";g.lineWidth=7;g.lineCap="round";g.shadowColor="#8affd1";g.shadowBlur=18;g.beginPath();g.moveTo(trail[0].x,trail[0].y);trail.forEach(p=>g.lineTo(p.x,p.y));g.stroke();g.shadowBlur=0}
  hazards.forEach(h=>{g.fillStyle="rgba(23,8,37,.78)";g.shadowColor="#9f4cff";g.shadowBlur=19;g.beginPath();g.arc(h.x,h.y,h.r,0,7);g.fill();g.shadowBlur=0});nodes.forEach((n,i)=>{g.shadowColor=i<next?"#8dffda":i===next?"#ffffff":"#9d9abf";g.shadowBlur=i===next?25:12;g.fillStyle=i<next?"#dffff3":i===next?"#fff":"#aba7cf";g.beginPath();g.arc(n.x,n.y,n.r,0,7);g.fill();g.shadowBlur=0;if(showing){g.fillStyle="#090a18";g.font="bold 16px system-ui";g.textAlign="center";g.textBaseline="middle";g.fillText(i+1,n.x,n.y)}})}
 newRound();state.raf=requestAnimationFrame(loop)
}

/* 3 · WHISPERING WOLF — audio sequences, reverse echoes and fear meter */
function startWolf(){
 box.innerHTML=gameHeader("EL LOBO ESCUCHA")+`<canvas class="game" id="c" width="540" height="470"></canvas><div class="lanes"><button class="lane-btn" data-l="0"><strong>◀</strong><small>GRAVE</small></button><button class="lane-btn" data-l="1"><strong>●</strong><small>MEDIO</small></button><button class="lane-btn" data-l="2"><strong>▶</strong><small>AGUDO</small></button></div>`;
 const c=$("#c"),g=c.getContext("2d"),W=c.width,H=c.height,pads=$$(".lane-btn");let round=0,seq=[],input=[],playing=true,fear=0,combo=0,reverse=false,deadline=0,last=performance.now(),ended=false;
 function flash(i,d=280){pads[i].style.background="rgba(167,255,222,.25)";AudioFX.cue(i);timer(setTimeout(()=>pads[i].style.background="",d))}
 function next(){round++;if(round>9){ended=true;finish(state.score+220,"El lobo inclinó la cabeza","Reconoció tu melodía y abrió el camino del bosque.","◢");return}seq=Array.from({length:2+Math.floor(round/2)},()=>Math.floor(Math.random()*3));input=[];playing=true;reverse=round%3===0;$("#hud").innerHTML=`<span class="hud-chip">MIEDO ${fear}/3</span><span>${reverse?"ECO INVERTIDO · ESCUCHA":"RONDA "+round+" · ESCUCHA"}</span><span class="hud-chip">×${combo}</span>`;progress((round-1)/9*100);seq.forEach((n,i)=>timer(setTimeout(()=>flash(n,330),650+i*560)));timer(setTimeout(()=>{playing=false;deadline=performance.now()+Math.max(3800,6500-round*230);$("#hud").textContent=reverse?"REPITE AL REVÉS":"REPITE LA MELODÍA"},800+seq.length*560))}
 function wrong(){fear++;combo=0;AudioFX.sfx("bad");haptic([20,30,20]);comboToast("El lobo se acerca");if(fear>=3){ended=true;finish(state.score,"El lobo despertó","Llegaste a la ronda "+round+". Cada tercer eco debe repetirse al revés.","◢")}else timer(setTimeout(next,700))}
 pads.forEach((b,i)=>b.onclick=()=>{if(playing||ended)return;flash(i,180);input.push(i);const target=reverse?[...seq].reverse():seq;if(input[input.length-1]!==target[input.length-1]){playing=true;wrong();return}if(input.length===target.length){playing=true;const remain=Math.max(0,deadline-performance.now()),pts=Math.round(55+round*14+remain/80+combo*9);score(state.score+pts);combo++;AudioFX.sfx(combo>2?"perfect":"good");haptic(12);comboToast(reverse?"Eco dominado":"Melodía ×"+combo);timer(setTimeout(next,650))}});
 function loop(now){if(ended)return;const dt=Math.min(.035,(now-last)/1000);last=now;if(!playing&&now>deadline){playing=true;wrong()}draw(now);state.raf=requestAnimationFrame(loop)}
 function draw(now){const bg=g.createLinearGradient(0,0,0,H);bg.addColorStop(0,"#17302f");bg.addColorStop(1,"#05090d");g.fillStyle=bg;g.fillRect(0,0,W,H);for(let i=0;i<9;i++){const x=i*70-20;g.fillStyle="#07100e";g.beginPath();g.moveTo(x,H);g.lineTo(x+34,110+(i%3)*35);g.lineTo(x+70,H);g.fill()}const approach=fear/3;const size=95+approach*95;g.fillStyle="#030609";g.beginPath();g.arc(W/2,205,size,Math.PI,0);g.lineTo(W/2+size*.78,390);g.lineTo(W/2-size*.78,390);g.fill();const eyeY=230+approach*28,eyeGap=45+approach*25;g.shadowColor="#b9ffe1";g.shadowBlur=15+fear*8;g.fillStyle="#cffff0";[-1,1].forEach(s=>{g.beginPath();g.ellipse(W/2+s*eyeGap,eyeY,11+approach*5,4+approach*2,s*.2,0,7);g.fill()});g.shadowBlur=0;g.fillStyle="rgba(220,255,245,.5)";g.font="13px system-ui";g.textAlign="center";g.fillText(reverse?"EL ECO CAMINA HACIA ATRÁS":"ESCUCHA ANTES DE ELEGIR",W/2,55)}
 next();state.raf=requestAnimationFrame(loop)
}

/* 4 · MOON MOTHS — flock survival, wind, nectar chains and shadow predators */
function startMoths(){
 box.innerHTML=gameHeader("PROTEGE LA BANDADA")+`<canvas class="game" id="c" width="540" height="700"></canvas><div class="runner-help">Arrastra la luna · encadena flores sin dejar que las sombras toquen a las polillas</div>`;
 const c=$("#c"),g=c.getContext("2d"),W=c.width,H=c.height;let orb={x:W/2,y:H*.55,r:22},moths=Array.from({length:12},(_,i)=>({x:W/2+(Math.random()-.5)*80,y:H*.55+(Math.random()-.5)*80,vx:0,vy:0,p:i})),flowers=[],shadows=[],wind={x:0,y:0},left=55,last=performance.now(),fSpawn=.1,sSpawn=1.2,windTime=6,combo=0,comboClock=0,shield=0,drag=false,ended=false;
 c.onpointerdown=e=>{drag=true;c.setPointerCapture(e.pointerId);orb=point(e,c)};c.onpointermove=e=>{if(drag)orb=point(e,c)};c.onpointerup=c.onpointercancel=()=>drag=false;
 every(setInterval(()=>{left--;if(left<=0&&!ended){ended=true;finish(state.score+moths.length*18,"La bandada alcanzó el claro","Conservaste "+moths.length+" polillas y encadenaste hasta ×"+Math.max(1,combo)+" de néctar.","⋈")}},1000));
 function loop(now){if(ended)return;const dt=Math.min(.035,(now-last)/1000);last=now;fSpawn-=dt;sSpawn-=dt;windTime-=dt;comboClock-=dt;shield=Math.max(0,shield-dt);if(comboClock<=0)combo=0;if(windTime<=0){const a=Math.random()*Math.PI*2,s=35+Math.random()*65;wind={x:Math.cos(a)*s,y:Math.sin(a)*s};windTime=4+Math.random()*4;comboToast("El viento cambió")}
  if(fSpawn<=0){flowers.push({x:45+Math.random()*(W-90),y:70+Math.random()*(H-140),r:17,kind:Math.random()<.12?"moon":"flower",life:9});fSpawn=.42+Math.random()*.72}
  if(sSpawn<=0){shadows.push({x:Math.random()<.5?-55:W+55,y:70+Math.random()*(H-140),r:25+Math.random()*20,vx:Math.random()<.5?80+Math.random()*65:-80-Math.random()*65,vy:(Math.random()-.5)*45});if(shadows[shadows.length-1].x>W)shadows[shadows.length-1].vx=-Math.abs(shadows[shadows.length-1].vx);sSpawn=Math.max(.55,1.45-(55-left)*.012)+Math.random()*.7}
  moths.forEach((m,i)=>{const a=now*.0016+i*2.39,tx=orb.x+Math.cos(a)*(35+i%4*8),ty=orb.y+Math.sin(a*1.17)*(31+i%3*8);m.vx+=(tx-m.x)*dt*4.1+wind.x*dt;m.vy+=(ty-m.y)*dt*4.1+wind.y*dt;m.vx*=.935;m.vy*=.935;m.x=clamp(m.x+m.vx,7,W-7);m.y=clamp(m.y+m.vy,7,H-7)});
  flowers.forEach(f=>f.life-=dt);flowers=flowers.filter(f=>f.life>0);shadows.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt});shadows=shadows.filter(s=>s.x>-90&&s.x<W+90&&s.y>-90&&s.y<H+90);
  for(let i=flowers.length-1;i>=0;i--){const f=flowers[i],near=moths.filter(m=>Math.hypot(m.x-f.x,m.y-f.y)<f.r+12);if(near.length>=2){flowers.splice(i,1);combo++;comboClock=2.4;const mult=1+Math.min(combo,8)*.25;score(state.score+Math.round((f.kind==="moon"?24:7)*mult));if(f.kind==="moon"){shield=5;AudioFX.sfx("shield");comboToast("Luna protectora")}else{AudioFX.sfx("collect");if(combo%4===0)comboToast("Néctar ×"+combo)}haptic(5)}}
  if(shield<=0)for(let i=shadows.length-1;i>=0;i--){const s=shadows[i],idx=moths.findIndex(m=>Math.hypot(m.x-s.x,m.y-s.y)<s.r+9);if(idx>=0){moths.splice(idx,1);shadows.splice(i,1);combo=0;AudioFX.sfx("hit");haptic(28);comboToast("Una luz se apagó");if(!moths.length){ended=true;finish(state.score,"La noche tomó la bandada","Recoge lunas protectoras y mueve la guía con trazos suaves.","⋈");return}}}
  progress((55-left)/55*100);$("#hud").innerHTML=`<span class="hud-chip">⋈ ${moths.length}</span><span>${left}s · VIENTO ${Math.round(Math.hypot(wind.x,wind.y))}</span><span class="hud-chip">×${Math.max(1,combo)}${shield?" · ESCUDO":""}</span>`;draw(now);state.raf=requestAnimationFrame(loop)}
 function draw(now){const bg=g.createRadialGradient(orb.x,orb.y,15,W/2,H/2,H*.7);bg.addColorStop(0,"#28364e");bg.addColorStop(.45,"#11182a");bg.addColorStop(1,"#050811");g.fillStyle=bg;g.fillRect(0,0,W,H);g.strokeStyle="rgba(170,205,255,.12)";g.lineWidth=3;for(let i=0;i<10;i++){const x=(i*83+now*.02*wind.x/50)%650-50;g.beginPath();g.moveTo(x,0);g.lineTo(x+wind.x*1.2,H);g.stroke()}
  flowers.forEach(f=>{g.shadowColor=f.kind==="moon"?"#ffe6a0":"#ffb2d6";g.shadowBlur=20;g.fillStyle=f.kind==="moon"?"#fff0b6":"#f6c0dc";g.font=f.kind==="moon"?"31px system-ui":"27px system-ui";g.textAlign="center";g.fillText(f.kind==="moon"?"☾":"✾",f.x,f.y+10);g.shadowBlur=0});shadows.forEach(s=>{g.fillStyle="rgba(2,3,9,.82)";g.shadowColor="#7f4ca5";g.shadowBlur=17;g.beginPath();g.arc(s.x,s.y,s.r,0,7);g.fill();g.shadowBlur=0});
  if(shield){g.strokeStyle="rgba(255,233,164,.65)";g.lineWidth=4;g.beginPath();g.arc(orb.x,orb.y,64+Math.sin(now*.006)*5,0,7);g.stroke()}g.shadowColor="#ffe6a3";g.shadowBlur=32;g.fillStyle="#fff4c6";g.beginPath();g.arc(orb.x,orb.y,orb.r,0,7);g.fill();g.shadowBlur=0;moths.forEach((m,i)=>{g.save();g.translate(m.x,m.y);g.rotate(Math.atan2(m.vy,m.vx));g.fillStyle="#edfff9";g.shadowColor="#9fffe1";g.shadowBlur=12;g.beginPath();g.ellipse(-5,0,8,4,-.3,0,7);g.ellipse(5,0,8,4,.3,0,7);g.fill();g.restore()});g.shadowBlur=0}
 state.raf=requestAnimationFrame(loop)
}

/* 5 · THE SEED SINGS — timed rhythm memory and procedural tree */
function startSeed(){
 box.innerHTML=gameHeader("ESCUCHA LAS RAÍCES")+`<canvas class="game" id="tree" width="540" height="390"></canvas><div class="panel"><div class="echo-grid"><button class="echo" data-i="0">❄</button><button class="echo" data-i="1">☾</button><button class="echo" data-i="2">✦</button><button class="echo" data-i="3">❀</button></div></div>`;
 const buttons=$$(".echo"),c=$("#tree"),g=c.getContext("2d"),freq=[261.63,329.63,392,523.25];let round=0,seq=[],expected=[],idx=0,phase="play",lives=3,perfects=0,branches=[],flowers=[],ended=false,beat=620,userStart=0;
 function flash(i,d=230){buttons[i].classList.add("on");AudioFX.note(freq[i],.3,.095,"sine");timer(setTimeout(()=>buttons[i].classList.remove("on"),d))}
 function grow(grade){const side=branches.length%2?-1:1,y=330-branches.length*18,x2=270+side*(55+Math.random()*70);branches.push({x1:270,y1:y+20,x2,y2:y-35});if(grade==="PERFECTO")flowers.push({x:x2,y:y-35,c:["#b6ffda","#92eaff","#c2a8ff","#f6b5d5"][flowers.length%4]})}
 function nextRound(){round++;if(round>7){ended=true;finish(state.score+perfects*20,"El árbol aprendió tu pulso","Crecieron "+branches.length+" ramas y "+perfects+" flores perfectas.","⌇");return}seq=Array.from({length:2+round},()=>Math.floor(Math.random()*4));idx=0;phase="play";beat=Math.max(390,650-round*35);$("#hud").innerHTML=`<span class="hud-chip">${"◆".repeat(lives)}${"◇".repeat(3-lives)}</span><span>RAMA ${round}/7 · ESCUCHA</span><span class="hud-chip">${beat}ms</span>`;progress((round-1)/7*100);seq.forEach((n,i)=>timer(setTimeout(()=>flash(n),600+i*beat)));timer(setTimeout(startUser,800+seq.length*beat))}
 function startUser(){phase="count";let count=3;$("#hud").textContent="ENTRA EN EL PULSO · 3";const id=every(setInterval(()=>{count--;if(count>0){$("#hud").textContent="ENTRA EN EL PULSO · "+count;AudioFX.note(196,.08,.035,"triangle")}else{clearInterval(id);phase="user";userStart=performance.now()+beat;expected=seq.map((n,i)=>({n,t:userStart+i*beat}));idx=0;$("#hud").textContent="TOCA CON EL LATIDO";AudioFX.note(392,.11,.05,"triangle")}},beat))}
 function miss(reason){lives--;phase="pause";AudioFX.sfx("bad");haptic([20,25,20]);comboToast(reason);if(lives<=0){ended=true;finish(state.score,"La semilla volvió a dormir","Llegaste a la rama "+round+". Escucha el tempo y espera la cuenta regresiva.","⌇")}else timer(setTimeout(nextRound,750))}
 buttons.forEach((b,i)=>b.onclick=()=>{if(phase!=="user"||ended)return;const now=performance.now(),ex=expected[idx];flash(i,170);if(!ex||i!==ex.n){miss("Símbolo incorrecto");return}const diff=Math.abs(now-ex.t);if(diff>260){miss("Fuera del pulso");return}const grade=diff<75?"PERFECTO":diff<155?"BIEN":"CERCA";const pts=grade==="PERFECTO"?35:grade==="BIEN"?22:12;score(state.score+pts+round*2);if(grade==="PERFECTO"){perfects++;AudioFX.sfx("perfect");haptic(7)}else AudioFX.sfx("good");grow(grade);comboToast(grade);idx++;draw();if(idx===seq.length){phase="pause";timer(setTimeout(nextRound,750))}});
 function draw(){const bg=g.createLinearGradient(0,0,0,c.height);bg.addColorStop(0,"#16372e");bg.addColorStop(1,"#050d0a");g.fillStyle=bg;g.fillRect(0,0,c.width,c.height);g.fillStyle="rgba(150,255,198,.06)";for(let i=0;i<9;i++){g.beginPath();g.arc(50+i*65,80+(i%3)*45,45,0,7);g.fill()}g.strokeStyle="#c9ead8";g.lineCap="round";g.lineWidth=11;g.beginPath();g.moveTo(270,370);g.lineTo(270,330-branches.length*16);g.stroke();branches.forEach((b,i)=>{g.strokeStyle=`rgba(200,240,221,${.55+i*.025})`;g.lineWidth=5;g.beginPath();g.moveTo(b.x1,b.y1);g.quadraticCurveTo(270,b.y2,b.x2,b.y2);g.stroke()});flowers.forEach(f=>{g.shadowColor=f.c;g.shadowBlur=18;g.fillStyle=f.c;g.beginPath();for(let a=0;a<6;a++){const ang=a/6*Math.PI*2;g.arc(f.x+Math.cos(ang)*8,f.y+Math.sin(ang)*8,5,0,7)}g.fill();g.shadowBlur=0});g.fillStyle="#d9ffe7";g.shadowColor="#8cffbd";g.shadowBlur=22;g.beginPath();g.ellipse(270,350,12,18,0,0,7);g.fill();g.shadowBlur=0}
 draw();nextRound()
}

/* 6 · DANCE IN THE STORM — waves, energy, shield burst and lane patterns */
function startStorm(){
 box.innerHTML=gameHeader("LA TORMENTA DESPIERTA")+`<canvas class="game" id="c" width="540" height="720"></canvas><div class="lanes"><button class="lane-btn" data-m="-1"><strong>←</strong><small>IZQUIERDA</small></button><button class="lane-btn" data-m="0"><strong>●</strong><small>CENTRO</small></button><button class="lane-btn" data-m="1"><strong>→</strong><small>DERECHA</small></button></div><button class="primary" id="stormBurst" style="margin-top:8px">EXPLOSIÓN DE LUZ · 0%</button>`;
 const c=$("#c"),g=c.getContext("2d"),W=c.width,H=c.height;let lane=1,targetLane=1,items=[],hearts=3,energy=0,shield=0,elapsed=0,last=performance.now(),spawn=.2,pattern=0,ended=false,sx=0;
 function wave(){return elapsed<15?"LLUVIA":elapsed<30?"VIENTO":elapsed<45?"RELÁMPAGOS":"FURIA DEL CIELO"}
 function move(d){targetLane=clamp(targetLane+d,0,2);AudioFX.sfx("jump");haptic(6)}
 $$('[data-m]').forEach(b=>b.onclick=()=>{const m=+b.dataset.m;m===0?targetLane=1:move(m)});c.onpointerdown=e=>sx=e.clientX;c.onpointerup=e=>{const dx=e.clientX-sx;if(Math.abs(dx)>35)move(dx>0?1:-1)};
 function burst(){if(energy<100||ended)return;energy=0;shield=4;items.forEach(o=>{if(o.bad)score(state.score+4)});items=[];AudioFX.sfx("shield");haptic([20,25,20,25,35]);comboToast("El cielo se abrió")}
 $("#stormBurst").onclick=burst;
 function addPattern(){pattern++;const difficulty=1+Math.floor(elapsed/15);if(pattern%5===0){const safe=Math.floor(Math.random()*3);for(let l=0;l<3;l++)if(l!==safe)items.push({lane:l,y:-50,v:230+difficulty*35,bad:true,r:18})}else if(Math.random()<.35){const l=Math.floor(Math.random()*3);items.push({lane:l,y:-50,v:190+difficulty*30,bad:false,r:18,kind:Math.random()<.15?"shield":"bolt"})}else items.push({lane:Math.floor(Math.random()*3),y:-50,v:210+difficulty*42,bad:true,r:16+Math.random()*10})}
 function damage(){if(shield>0)return;hearts--;AudioFX.sfx("hit");haptic(30);shield=1;energy=Math.max(0,energy-20);if(hearts<=0){ended=true;finish(state.score,"La tormenta apagó tu paso","Llegaste a "+wave().toLowerCase()+". Guarda la explosión para las paredes de lluvia.","ϟ")}}
 function loop(now){if(ended)return;const dt=Math.min(.035,(now-last)/1000);last=now;elapsed+=dt;spawn-=dt;shield=Math.max(0,shield-dt);lane+=(targetLane-lane)*Math.min(1,dt*11);if(spawn<=0){addPattern();spawn=Math.max(.18,.52-elapsed*.004)+Math.random()*.22}items.forEach(o=>o.y+=o.v*dt);
  const px=(lane+.5)*W/3,py=620;for(let i=items.length-1;i>=0;i--){const o=items[i],ox=(o.lane+.5)*W/3;if(o.y>H+50){items.splice(i,1);continue}if(Math.abs(ox-px)<42&&Math.abs(o.y-py)<42){items.splice(i,1);if(o.bad)damage();else if(o.kind==="shield"){shield=5;energy=clamp(energy+25,0,100);AudioFX.sfx("shield");comboToast("Escudo lunar")}else{energy=clamp(energy+18,0,100);score(state.score+16+Math.floor(elapsed/10)*4);AudioFX.sfx("collect");haptic(6)}}}
  if(elapsed>=60){ended=true;finish(state.score+Math.round(elapsed*4)+hearts*60,"Bailaste hasta que volvió la calma","Sobreviviste las cuatro oleadas con "+hearts+" corazones.","ϟ");return}score(state.score+dt*2.2);progress(elapsed/60*100);$("#stormBurst").textContent=`EXPLOSIÓN DE LUZ · ${Math.round(energy)}%`;$("#stormBurst").style.opacity=energy>=100?1:.62;$("#hud").innerHTML=`<span class="hud-chip">${"❤".repeat(hearts)}${"♡".repeat(3-hearts)}</span><span>${wave()} · ${Math.ceil(60-elapsed)}s</span><span class="hud-chip">${shield?"ESCUDO":"✦ "+Math.round(energy)}</span>`;draw(now);state.raf=requestAnimationFrame(loop)}
 function draw(now){const rage=elapsed/60,bg=g.createLinearGradient(0,0,0,H);bg.addColorStop(0,`rgb(${25+rage*25},${37+rage*10},${61+rage*25})`);bg.addColorStop(1,"#05080e");g.fillStyle=bg;g.fillRect(0,0,W,H);g.strokeStyle="rgba(170,196,235,.12)";for(let i=1;i<3;i++){g.beginPath();g.moveTo(i*W/3,0);g.lineTo(i*W/3,H);g.stroke()}for(let i=0;i<22;i++){const x=(i*53+now*.16)%650-60,y=(i*97+now*.38)%800-60;g.strokeStyle="rgba(170,205,255,.2)";g.lineWidth=3;g.beginPath();g.moveTo(x,y);g.lineTo(x-15,y+40);g.stroke()}
  items.forEach(o=>{const x=(o.lane+.5)*W/3;if(o.bad){g.strokeStyle="#62758d";g.lineWidth=8;g.beginPath();g.moveTo(x,o.y-28);g.lineTo(x-12,o.y+27);g.stroke()}else{g.shadowColor=o.kind==="shield"?"#b6ffda":"#ffe09a";g.shadowBlur=22;g.fillStyle=o.kind==="shield"?"#d8ffeb":"#fff0b8";g.font="39px system-ui";g.textAlign="center";g.fillText(o.kind==="shield"?"◯":"ϟ",x,o.y+12);g.shadowBlur=0}});if(shield>0){g.strokeStyle="rgba(182,255,218,.65)";g.lineWidth=5;g.beginPath();g.arc((lane+.5)*W/3,620,42+Math.sin(now*.008)*4,0,7);g.stroke()}g.shadowColor="#a6ffe0";g.shadowBlur=30;g.fillStyle="#f0fff9";g.beginPath();g.arc((lane+.5)*W/3,620,25,0,7);g.fill();g.shadowBlur=0}
 state.raf=requestAnimationFrame(loop)
}